# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ben Farmer
title: Junior Developer at Cloudm
email: ben@benfarmer.dev
website: BenFarmer.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  BenFarmer3
instagram_username: ben_farmer3
linkedin_username: farmerb

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | 
  Hi, my name's Ben and I'm a junior software developer currently working at Cloudm.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CloudM
        link: CloudM.io
        # link_text: boringcompany.com
        sub_title: Junior Software Developer
        caption: Sep 2021 - Present
        description: |
          Cloud Migrate
            - Tech: C#, .NET, HTML, AngularJs, Razor Pages, PowerShell, Nunit, Moq
            - Worked on a major product for migrating user data to and from multiple different tenants.
            -	Solely responsible for a UI overhaul to every page of the product to be more consistent with the other products within the Cloudm product range using CSS, HTML and AngularJS.
            -	Implemented a feature to allow users to use Google JSON service account keys.
            -	Updated implementations of basic authentication to use modern authentication.
            -	Communicated with customers on technical support, providing information to solve their issues or log tickets within Jira to escalate and provide fixes.
            -	Used Nunit and Moq to develop unit and integration tests.


          Custom Software/Builds
            - Tech: PowerShell, C# .net
            -	Wrote PowerShell scripts for the Government of Virginia to delete 35,000+ wrongly created user contacts saving them hundreds of hours in labour time.
            -	Reorganised 700+ users email folder structures to be compatible with Cloudm Migrate, saving the company an estimated xXXX of organizing.
            -	Communicated with customers to get detailed requirements.  


          Automation Tests
            -	Tech: Python, Microsoft Graph, Selenium
            -	Implemented standardized automation tests in Python using Selenium for Microsoft Teams migrations. 
            -	Generated and deleted teams users along with data for each of them using the Microsoft Graph API.

            
          Test Hub
            -	Tech: Python, Flask, Google cloud
            -	Developed a new test hub website collating all CI build results and allowing developers streamlining the process for viewing and downloading results.
      - layout: left
        title: Newcastle Univercity
        link: ncl.ac.uk
        # link_text: boringcompany.com
        sub_title: Programming And Mathematics Tutor
        caption: Sep 2021 - Aug 2021
        description: |
          
  



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Implementing cryptographic methods into the IoT
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/benfarmer3/IFogSimCryptographyV1.0
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
